# @package _global_
defaults:
  - basic_oc_base
  - /prior: gauss
  - /sde: vp_10
  - /model@generative_ctrl: score
  - /loss: reference_sde
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.EulerDDS
