# @package _global_
defaults:
  - basic_oc_base
  - /prior: gauss
  - /sde: 
  - /model@generative_ctrl: score
  - /loss: exponential_sde
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.DDS

train_timesteps:
  rescale_t: "cosine"
  steps: 
  end: 25.6 
  dt: 0.05

train_steps: 11000 
train_batch_size: 300
eval_batch_size: 2000

optim:
  lr: 0.001

prior:
  scale: ${loss.sigma}